import hms.patient.slippdf.AdvancePaymentSlippdf;

import java.io.FileOutputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.Calendar;

import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

public class reportgen {

	int idSTR;
	public String outfile;
	private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 20);
	private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 24);
	private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 16);
	private static Font tableFont = new Font(Font.FontFamily.TIMES_ROMAN, 7,
			Font.BOLD);
	private static Font tableFontCell = new Font(Font.FontFamily.TIMES_ROMAN, 7);

	String testSTR, UserSTR, FromSTR, toSTR;

	public static void main(String[] arg) {
		new reportgen();
	}

	public reportgen() {
		saveAndVarify();
	}

	public void saveAndVarify() {

		String filename = "sss.pdf";

		outfile = "C:/Users/Sukhpal/Desktop/52.pdf";
		try {
			Document document = new Document(PageSize.A4, 50, 0, 50, 0);
			PdfWriter.getInstance(document, new FileOutputStream(outfile));
			document.open();
			document.setPageCount(1);
			createTable1(document);
			document.close();
		} catch (Exception e) {
			// TODO: handle exception
			System.out.print(e + "");
		}

	}

	

	private void createTable1(Document subCatPart) throws DocumentException,
			MalformedURLException, IOException {
		java.net.URL imgURL = AdvancePaymentSlippdf.class
				.getResource("/icons/logo.png");
		java.net.URL imgURL1 = AdvancePaymentSlippdf.class
				.getResource("/icons/verify.png");
		Image image = Image.getInstance(imgURL);
		Image image1 = Image.getInstance(imgURL1);
		image.scalePercent(15);
		image.setAbsolutePosition(40, 720);
		image1.scalePercent(15);
		image1.setAbsolutePosition(200, 250);
		java.text.DateFormat.getDateTimeInstance().format(
				Calendar.getInstance().getTime());
		Paragraph preface = new Paragraph();
		// We add one empty line1
		preface.add(Chunk.NEWLINE);
		// Lets write a big header
		preface.add(image);
		preface.add(new Paragraph(
				"                                             FilterCheck - 06 v1.1",
				subFont));
		preface.add(new Paragraph(
				"\t"
						+ "                                                                             Serial No. : 16",
				smallBold));
		preface.setAlignment(Element.ALIGN_RIGHT);
		preface.add(Chunk.NEWLINE);
		Paragraph prefaceName = new Paragraph(new Paragraph(
				"Filter Test Report", catFont));
		prefaceName.setAlignment(Element.ALIGN_CENTER);
		preface.add(prefaceName);
		preface.add(Chunk.NEWLINE);
		// Will create: Report generated by: _name, _date
		// preface.add(new Paragraph(
		// "  Report Generated at: " + setterAndGetter.getCurrentDate()+",  "+
		// java.text.DateFormat.getTimeInstance().format(Calendar.getInstance().getTime()),smallBold));

		preface.add(new Paragraph(
				"  Test Performed on   : 09-Mar-2015, 11:04:07 ", smallBold));
		preface.add("");
		PdfPTable table = new PdfPTable(2);
		table.setWidthPercentage(100);
		table.getDefaultCell().setBorder(0);
		table.addCell(new Phrase("  Serial No.  ", smallBold));
		table.addCell(new Phrase(":   52", smallBold));

		table.addCell(new Phrase("  Test Type", smallBold));
		table.addCell(new Phrase(":   Bubble Point Test(Standard)", smallBold));

		table.addCell(new Phrase("  Production Area", smallBold));
		table.addCell(new Phrase(":   NA", smallBold));

		table.addCell(new Phrase("  Product Name", smallBold));
		table.addCell(new Phrase(":   ABC", smallBold));

		table.addCell(new Phrase("  Product Lot No.", smallBold));
		table.addCell(new Phrase(":   123", smallBold));

		table.addCell(new Phrase("  Filter Cat No.", smallBold));
		table.addCell(new Phrase(":   DKS", smallBold));

		table.addCell(new Phrase("  Filter Lot No.", smallBold));
		table.addCell(new Phrase(":   DK2704-094", smallBold));

		table.addCell(new Phrase("  Wetting Fluid", smallBold));
		table.addCell(new Phrase(":   WATER", smallBold));

		table.addCell(new Phrase("  Pore Size", smallBold));
		table.addCell(new Phrase(":   0.2 µm", smallBold));

		table.addCell(new Phrase("  Filter Size", smallBold));
		table.addCell(new Phrase(":   1 inch", smallBold));
		
		table.addCell(new Phrase("  Min. Bubble point value", smallBold));
		table.addCell(new Phrase(":   50 psi", smallBold));
		
		table.addCell(new Phrase("  Test Value", smallBold));
		table.addCell(new Phrase(":   59.71 psi" + "", smallBold));

		table.addCell(new Phrase("  Test Result", smallBold));
		table.addCell(new Phrase(":   " + "Passed", smallBold));

		preface.add(table);
		preface.add(Chunk.NEWLINE);
		preface.add(Chunk.NEWLINE);
//		preface.add(new Paragraph("     " + "Sandeep", smallBold));
//		preface.add(new Paragraph("  (Test Operator)", smallBold));
//		preface.add(new Paragraph("  " + "03-July-2014", smallBold));
		
		
		PdfPTable table2 = new PdfPTable(2);
		table2.setWidthPercentage(100);
		table2.getDefaultCell().setBorder(0);
		
		PdfPTable table3 = new PdfPTable(1);
		table3.setWidthPercentage(50);
		table3.getDefaultCell().setBorder(0);
		
		PdfPTable table4 = new PdfPTable(1);
		table4.setWidthPercentage(50);
		table4.getDefaultCell().setBorder(0);
		
		PdfPCell c=new PdfPCell(new Phrase("  Admin", smallBold));
		c.setBorder(Rectangle.NO_BORDER);
		table3.addCell(c);
		 c=new PdfPCell(new Phrase("(Test Operator)", smallBold));
		 c.setBorder(Rectangle.NO_BORDER);
		 table3.addCell(c);
		 c=new PdfPCell(new Phrase("  09-Mar-2015", smallBold));
		 c.setBorder(Rectangle.NO_BORDER);
		 table3.addCell(c);
		 
//		 c=new PdfPCell(new Phrase("(Test Operator)", smallBold));
//		 c.setHorizontalAlignment(Element.ALIGN_CENTER);
//		 c.setBorder(Rectangle.NO_BORDER);
//		 table4.addCell(c);
//		 c=new PdfPCell(new Phrase("(Test Operator)", smallBold));
//		 c.setHorizontalAlignment(Element.ALIGN_CENTER);
//		 c.setBorder(Rectangle.NO_BORDER);
//		 table4.addCell(c);
//		 c=new PdfPCell(new Phrase("03-July-2014", smallBold));
//		 c.setHorizontalAlignment(Element.ALIGN_CENTER);
//		 c.setBorder(Rectangle.NO_BORDER);
//		 table4.addCell(c);
		 
		 table2.addCell(table3);
		 table2.addCell(table4);
		 preface.add(table2);
		subCatPart.add(preface);

	}

}
